//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ADLX_AFMF_ALGORITHM {
  AFMF_ALGORITHM_AUTO = 0,
  AFMF_ALGORITHM_ENHANCED,
  AFMF_ALGORITHM_STANDARD
}
