//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ADLX_AFMF_FAST_MOTION_RESP {
  AFMF_RESP_REPEAT_FRAMES = 0,
  AFMF_RESP_BLENDED_FRAMES = 1
}
