//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ADLX_VARIABLE_GRAPHICS_MEMORY_MODE {
  VARIABLE_GRAPHICS_MEMORY_MODE_AUTO = 0,
  VARIABLE_GRAPHICS_MEMORY_MODE_CUSTOM = 1
}
