//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IADLXVariableGraphicsMemory : IADLXInterface {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXVariableGraphicsMemory(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXVariableGraphicsMemory_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXVariableGraphicsMemory obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IADLXVariableGraphicsMemory obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXVariableGraphicsMemory(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXVariableGraphicsMemory_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT IsSupported(SWIGTYPE_p_bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXVariableGraphicsMemory_IsSupported(swigCPtr, SWIGTYPE_p_bool.getCPtr(supported));
    return ret;
  }

  public virtual ADLX_RESULT GetDefaultOption(SWIGTYPE_p_p_adlx__IADLXVariableGraphicsMemoryOption ppOption) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXVariableGraphicsMemory_GetDefaultOption(swigCPtr, SWIGTYPE_p_p_adlx__IADLXVariableGraphicsMemoryOption.getCPtr(ppOption));
    return ret;
  }

  public virtual ADLX_RESULT GetOption(SWIGTYPE_p_p_adlx__IADLXVariableGraphicsMemoryOption ppOption) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXVariableGraphicsMemory_GetOption(swigCPtr, SWIGTYPE_p_p_adlx__IADLXVariableGraphicsMemoryOption.getCPtr(ppOption));
    return ret;
  }

  public virtual ADLX_RESULT GetAvailableOptions(SWIGTYPE_p_p_adlx__IADLXVariableGraphicsMemoryOptionList ppOptions) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXVariableGraphicsMemory_GetAvailableOptions(swigCPtr, SWIGTYPE_p_p_adlx__IADLXVariableGraphicsMemoryOptionList.getCPtr(ppOptions));
    return ret;
  }

  public virtual ADLX_RESULT SetOption(IADLXVariableGraphicsMemoryOption pOption) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXVariableGraphicsMemory_SetOption(swigCPtr, IADLXVariableGraphicsMemoryOption.getCPtr(pOption));
    return ret;
  }

}
