//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IADLXGPU3 : IADLXGPU2 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXGPU3(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXGPU3_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXGPU3 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IADLXGPU3 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXGPU3(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXGPU3_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT MicroArchitecture(SWIGTYPE_p_p_char microArchitecture) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU3_MicroArchitecture(swigCPtr, SWIGTYPE_p_p_char.getCPtr(microArchitecture));
    return ret;
  }

  public virtual ADLX_RESULT HighestVRAMBandwidth(SWIGTYPE_p_unsigned_int data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU3_HighestVRAMBandwidth(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(data));
    return ret;
  }

  public virtual ADLX_RESULT InvisibleVRAM(SWIGTYPE_p_unsigned_int data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU3_InvisibleVRAM(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(data));
    return ret;
  }

  public virtual ADLX_RESULT VisibleVRAM(SWIGTYPE_p_unsigned_int data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU3_VisibleVRAM(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(data));
    return ret;
  }

  public virtual ADLX_RESULT VRAMVendorRevId(SWIGTYPE_p_unsigned_int data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU3_VRAMVendorRevId(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(data));
    return ret;
  }

  public virtual ADLX_RESULT VRAMBandwidth(SWIGTYPE_p_unsigned_int data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU3_VRAMBandwidth(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(data));
    return ret;
  }

  public virtual ADLX_RESULT VRAMBitRate(SWIGTYPE_p_unsigned_int data) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU3_VRAMBitRate(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(data));
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedStressTest(SWIGTYPE_p_bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU3_IsSupportedStressTest(swigCPtr, SWIGTYPE_p_bool.getCPtr(supported));
    return ret;
  }

  public virtual ADLX_RESULT StartStressTest(IADLXGPUStressTestFinishedListener pGPUStressTestFinishedListener, uint duration) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU3_StartStressTest(swigCPtr, IADLXGPUStressTestFinishedListener.getCPtr(pGPUStressTestFinishedListener), duration);
    return ret;
  }

}
