//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IADLX3DAMDFluidMotionFrames1 : IADLX3DAMDFluidMotionFrames {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLX3DAMDFluidMotionFrames1(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLX3DAMDFluidMotionFrames1_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLX3DAMDFluidMotionFrames1 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IADLX3DAMDFluidMotionFrames1 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLX3DAMDFluidMotionFrames1(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLX3DAMDFluidMotionFrames1_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedAlgorithm(SWIGTYPE_p_bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLX3DAMDFluidMotionFrames1_IsSupportedAlgorithm(swigCPtr, SWIGTYPE_p_bool.getCPtr(supported));
    return ret;
  }

  public virtual ADLX_RESULT GetAlgorithm(SWIGTYPE_p_adlx__ADLX_AFMF_ALGORITHM algorithm) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLX3DAMDFluidMotionFrames1_GetAlgorithm(swigCPtr, SWIGTYPE_p_adlx__ADLX_AFMF_ALGORITHM.getCPtr(algorithm));
    return ret;
  }

  public virtual ADLX_RESULT SetAlgorithm(ADLX_AFMF_ALGORITHM algorithm) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLX3DAMDFluidMotionFrames1_SetAlgorithm(swigCPtr, (int)algorithm);
    return ret;
  }

  public virtual ADLX_RESULT GetSearchMode(SWIGTYPE_p_adlx__ADLX_AFMF_SEARCH_MODE_TYPE mode) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLX3DAMDFluidMotionFrames1_GetSearchMode(swigCPtr, SWIGTYPE_p_adlx__ADLX_AFMF_SEARCH_MODE_TYPE.getCPtr(mode));
    return ret;
  }

  public virtual ADLX_RESULT SetSearchMode(ADLX_AFMF_SEARCH_MODE_TYPE mode) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLX3DAMDFluidMotionFrames1_SetSearchMode(swigCPtr, (int)mode);
    return ret;
  }

  public virtual ADLX_RESULT GetPerformanceMode(SWIGTYPE_p_adlx__ADLX_AFMF_PERFORMANCE_MODE_TYPE mode) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLX3DAMDFluidMotionFrames1_GetPerformanceMode(swigCPtr, SWIGTYPE_p_adlx__ADLX_AFMF_PERFORMANCE_MODE_TYPE.getCPtr(mode));
    return ret;
  }

  public virtual ADLX_RESULT SetPerformanceMode(ADLX_AFMF_PERFORMANCE_MODE_TYPE mode) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLX3DAMDFluidMotionFrames1_SetPerformanceMode(swigCPtr, (int)mode);
    return ret;
  }

  public virtual ADLX_RESULT GetFastMotionResponse(SWIGTYPE_p_adlx__ADLX_AFMF_FAST_MOTION_RESP response) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLX3DAMDFluidMotionFrames1_GetFastMotionResponse(swigCPtr, SWIGTYPE_p_adlx__ADLX_AFMF_FAST_MOTION_RESP.getCPtr(response));
    return ret;
  }

  public virtual ADLX_RESULT SetFastMotionResponse(ADLX_AFMF_FAST_MOTION_RESP response) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLX3DAMDFluidMotionFrames1_SetFastMotionResponse(swigCPtr, (int)response);
    return ret;
  }

}
