//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IADLXVariableGraphicsMemoryOption : IADLXInterface {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXVariableGraphicsMemoryOption(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXVariableGraphicsMemoryOption_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXVariableGraphicsMemoryOption obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IADLXVariableGraphicsMemoryOption obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXVariableGraphicsMemoryOption(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXVariableGraphicsMemoryOption_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT Name(SWIGTYPE_p_p_char optionName) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXVariableGraphicsMemoryOption_Name(swigCPtr, SWIGTYPE_p_p_char.getCPtr(optionName));
    return ret;
  }

  public virtual ADLX_RESULT Mode(SWIGTYPE_p_adlx__ADLX_VARIABLE_GRAPHICS_MEMORY_MODE mode) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXVariableGraphicsMemoryOption_Mode(swigCPtr, SWIGTYPE_p_adlx__ADLX_VARIABLE_GRAPHICS_MEMORY_MODE.getCPtr(mode));
    return ret;
  }

  public virtual ADLX_RESULT MemoryCarved(SWIGTYPE_p_double memoryCarvedGb) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXVariableGraphicsMemoryOption_MemoryCarved(swigCPtr, SWIGTYPE_p_double.getCPtr(memoryCarvedGb));
    return ret;
  }

  public virtual ADLX_RESULT MemoryRemaining(SWIGTYPE_p_double memoryRemainingGb) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXVariableGraphicsMemoryOption_MemoryRemaining(swigCPtr, SWIGTYPE_p_double.getCPtr(memoryRemainingGb));
    return ret;
  }

}
